apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

namespace: open-cluster-management-observability

resources:
- namespace.yaml

secretGenerator:
- name: thanos-object-storage
  files:
  - thanos.yaml.secret
- name: multiclusterhub-operator-pull-secret
  envs:
  - pull-secret.secret
  type: kubernetes.io/dockerconfigjson
