- name: Patch to enable cluster backup operator
  k8s:
    definition:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: open-cluster-management
      spec:
        enableClusterBackup: true

- name: Create openshift oadp operator
  kubernetes.core.k8s:
    state: present
    template:
      - path: "backup-schedule.yml"
