-   id: detect-secrets
    name: Detect secrets
    description: Detects high entropy strings that are likely to be passwords.
    entry: detect-secrets-hook
    language: python
    # for backward compatibility
    files: .*
-   id: end-of-file-fixer
    name: fix end of files
    description: ensures that a file is either empty, or ends with one newline.
    entry: end-of-file-fixer
    language: python
    types: [text]
    stages: [commit, push, manual]
