---
# This is the reference playbook that is used to develop the flow.
# Another version of this playbook is also avaiable in the AOC project.

- hosts:
    localhost
  gather_facts: false
  connection: local

  vars:
    # The following line is necessary because the generated inventory file
    # has this set to true.  We don't need to use sudo for the following
    # operations.
    ansible_become: false
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  collections:
    - awx.awx
    - azure.azcollection

  tasks:
    - name: Include standard job templates and workflows
      ansible.builtin.include_role:
        name: ../roles/aap-controller-acm-workflow-setup
        tasks_from: main

    - name: Include DEV only job templates and workflows
      ansible.builtin.include_role:
        name: ../roles/aap-controller-acm-workflow-setup
        tasks_from: dev
      when: target == 'openshiftdev' or target == 'adecorte'
