- name: "Generate kubeconfig for {{ target_hosts }} host group"
  hosts: "{{ target_hosts }}"
  connection: local
  tasks:
  - include_tasks: ../roles/k8s-cluster-access/tasks/get-access.yml
  - include_tasks: ../roles/k8s-cluster-access/tasks/generate-kubeconfig.yml
