- name: "Manage Operators"
  hosts: "{{ target_hosts | default('all') }}"
  connection: local
  gather_facts: false
  tasks:
    - block:
        - include_tasks: ../roles/k8s-cluster-access/tasks/get-access.yml
          vars:
            rbac_template: ../k8s-rbac/operator-mgmt
        - include_role:
            name: ../roles/k8s-operator-mgmt
          ignore_errors: true
          with_items:
            - "../k8s-operators/automation-test-keycloak"
            - "../k8s-operators/automation-test-etcd"
            # - "../k8s-operators/automation-test-nginx"
            # - "../operators/ansible-automation-platform-operator"
            # - "../operators/cert-manager"
            # - "../operators/keycloak-operator"
            # - "../operators/nginx-ingress-operator"
      always:
        - include_tasks: ../roles/k8s-cluster-access/tasks/remove-access.yml
          ignore_errors: true
