apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: automationcontroller
  name: automation-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: automationcontroller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: automationcontroller
    spec:
      containers:
      - args:
        - --web.listen-address=0.0.0.0:8080
        - --collector.disable-defaults
        - --web.telemetry-path=/api/v2/metrics
        - --collector.textfile
        - --web.disable-exporter-metrics
        - --collector.textfile.directory=/var/node_exporter/textfile
        image: quay.io/prometheus/node-exporter:latest
        imagePullPolicy: IfNotPresent
        name: automation-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: textfile
          mountPath: /var/node_exporter/textfile
      volumes:
      - name: textfile
        configMap:
          name: automation-controller
