apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ansible-automation-platform

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - ns.yaml

configMapGenerator:
- name: aap-metric-simulator
  files:
  - fake-aap-metrics.prom
generatorOptions:
  disableNameSuffixHash: true
