apiVersion: v1
kind: Service
metadata:
  name: aap-metric-simulator
  labels:
    app: aap-metric-simulator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: metrics
  selector:
    app: aap-metric-simulator
