phase_name: "OPENSHIFTDEV"
cluster_name: "testdev-aap"
azure_location: "westeurope"
azure_dns_root: "demo.az.red-chesterfield.com"
azure_dns_zone: "demo.az.red-chesterfield.com"
inventory_source_name: "azure-openshiftdev"
vault_uri: "https://kv-acmsre-team.vault.azure.net"
argocd_env: "testing"
parent_dns_zone: "demo.az.red-chesterfield.com" # Parent public DNS zone
parent_dns_zone_resource_group: "domain" # RG for parent public DNS zone
