phase_name: "RHAAPPROD"
cluster_name: "acm5"
azure_resource_group: "rg-acm"
azure_cluster_resource_group: "rg-acm-cluster"
azure_location: "eastus"
azure_dns_root: mgmt.ansiblecloud.com
azure_dns_zone: "az.mgmt.ansiblecloud.com"
inventory_source_name: "azure-rhaapprod"
vault_uri: "https://kv-aoc-team.vault.azure.net/" #TODO CHECK
argocd_env: "prod"
