apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: identity-management-configuration-for-kubernetes-sub
  namespace: idp-mgmt-config
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: idp-mgmt-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace