apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-mgmt
rules:
  - apiGroups:
      - operators.coreos.com
      - packages.operators.coreos.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - '*'
