apiVersion: v1
kind: Namespace
metadata:
  name: {{ cluster_name }}
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    cluster.open-cluster-management.io/clusterset: default
    name: {{ cluster_name }}
    vendor: auto-detect
  name: {{ cluster_name }}
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
