- name: "Removing managed ServiceAccount"
  ocmplus.cm.managed_serviceaccount:
    state: absent
    hub_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
    managed_cluster: "{{ hostvars[inventory_hostname].cluster_name }}"
    name: "{{ managed_serviceaccount.managed_serviceaccount.name }}"
    wait: true
    timeout: 60
